# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          overwrite-settings: false
      - name: Configure Maven settings
        uses: s4u/maven-settings-action@v4.0.0
        with:
          servers: '[{"id": "github", "username": "${{ github.actor }}"}, {"id": "prose-builder", "username": "${{ github.actor }}"}]'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy --file pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}